//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Gestiones
    {
        public int Codigo_Gestion { get; set; }
        public Nullable<int> Codigo_Usuario { get; set; }
        public Nullable<int> Codigo_Producto { get; set; }
        public string Tipo_Gestion { get; set; }
        public string Descripcion { get; set; }
        public Nullable<System.DateTime> Fecha_Gestion { get; set; }
        public string Estado { get; set; }
        public string Tipo_Producto { get; set; }
    
        public virtual TB_Producto TB_Producto { get; set; }
        public virtual TB_Usuario TB_Usuario { get; set; }
    }
}
