//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_Producto()
        {
            this.TB_Gestiones = new HashSet<TB_Gestiones>();
            this.TB_Transacciones = new HashSet<TB_Transacciones>();
        }
    
        public int Codigo_Producto { get; set; }
        public string Descripcion { get; set; }
        public string Tipo_Producto { get; set; }
        public Nullable<int> Codigo_Usuario { get; set; }
        public Nullable<decimal> Monto_Inicial { get; set; }
        public Nullable<int> Depositos { get; set; }
        public Nullable<int> Retiros { get; set; }
        public Nullable<decimal> Cuota { get; set; }
        public Nullable<System.DateTime> Fecha_Pago { get; set; }
        public Nullable<decimal> Monto_Capital { get; set; }
        public Nullable<decimal> Monto_Interes { get; set; }
        public Nullable<decimal> Saldo_Final { get; set; }
        public Nullable<int> Plazos { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Gestiones> TB_Gestiones { get; set; }
        public virtual TB_Usuario TB_Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Transacciones> TB_Transacciones { get; set; }
    }
}
