//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Transacciones
    {
        public int Codigo_Transaccion { get; set; }
        public Nullable<int> Codigo_Producto { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<System.DateTime> Fecha_Transaccion { get; set; }
        public string Tipo_Transaccion { get; set; }
        public Nullable<int> Codigo_Usuario { get; set; }
        public string Numero_Identidad { get; set; }
        public string Nombre_Completo { get; set; }
    
        public virtual TB_Producto TB_Producto { get; set; }
        public virtual TB_Usuario TB_Usuario { get; set; }
    }
}
