//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class TB_Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_Usuario()
        {
            this.TB_Gestiones = new HashSet<TB_Gestiones>();
            this.TB_Producto = new HashSet<TB_Producto>();
            this.TB_Transacciones = new HashSet<TB_Transacciones>();
        }
    
        [Display(Name ="Usuario")]
        public int Codigo_Usuario { get; set; }
        [DataType(DataType.Password)]
        public string Contraseña { get; set; }
        public string Numero_Identidad { get; set; }
        public string Nombre_Completo { get; set; }
        public string Genero { get; set; }
        public string Correo_Electronico { get; set; }
        public string Telefono { get; set; }
        public string Rol { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Gestiones> TB_Gestiones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Producto> TB_Producto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Transacciones> TB_Transacciones { get; set; }
    }
}
